#!/bin/sh

APTUPDATED=0
R=`./color 11`
W=`./color 15`
M=`./color 13`

if [ "$(id -u)" -ne 0 ]; then
        echo ${R}Please execute this as "${W}sudo sh install_unattended_upgrades${R}"${W}
        exit;
fi


aptUpdate () {
        if [ $APTUPDATED -ne 1 ]; then
                echo ${M}Updating repos${W}
                echo apt update
                echo apt -y upgrade
                echo apt -y install git
                APTUPDATED=1
        fi
}

checkPackage() {
        echo ${M}Checking for "$1".${W}
        var=$(sh get-list-of-installed-packages.sh | grep "$1" | grep -v man)
        if [ -z "$var" ]
        then
                echo ${M}"$1" is not installed.
                echo Correcting...
                aptUpdate
                apt install "$1"
        else
              echo ${M}"$1" is installed${W}
        fi
}

echo "${W}What time do you want to schedule automatic reboots?"
echo -n "Enter time in format like 00:00 to 23:59\n${M}>${W}"
read TIME
checkPackage unattended-upgrades

ex -s -c '14i|        "${distro_id}:${distro_codename}-updates";' -c x /etc/apt/apt.conf.d/50unattended-upgrades
echo "Unattended-Upgrade::Mail \"agustin@pollstar.com\";" >>/etc/apt/apt.conf.d/50unattended-upgrades
echo "Unattended-Upgrade::MailOnlyOnError \"true\";" >>/etc/apt/apt.conf.d/50unattended-upgrades
echo "Unattended-Upgrade::Remove-Unused-Kernel-Packages \"true\";" >>/etc/apt/apt.conf.d/50unattended-upgrades
echo "Unattended-Upgrade::Remove-Unused-Dependencies \"true\";" >>/etc/apt/apt.conf.d/50unattended-upgrades
echo "Unattended-Upgrade::Automatic-Reboot \"true\";" >>/etc/apt/apt.conf.d/50unattended-upgrades
echo "Unattended-Upgrade::Automatic-Reboot-Time \"${TIME}\";" >> /etc/apt/apt.conf.d/50unattended-upgrades

echo "APT::Periodic::Update-Package-Lists \"1\";" >> /etc/apt/apt.conf.d/20auto-upgrades
echo "APT::Periodic::Download-Upgradeable-Packages \"1\";" >> /etc/apt/apt.conf.d/20auto-upgrades
echo "APT::Periodic::AutocleanInterval \"7\";" >> /etc/apt/apt.conf.d/20auto-upgrades
echo "APT::Periodic::Unattended-Upgrade \"1\";" >> /etc/apt/apt.conf.d/20auto-upgrades
chmod 644 /etc/apt/apt.conf.d/20auto-upgrades
echo
echo Updates made to:
echo /etc/apt/apt.conf.d/50unattended-upgrades
echo /etc/apt/apt.conf.d/20auto-upgrades
echo

